name: Deploy react application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     

      - name: Build Docker Image
        run: docker build -t ritik9135/reactjs-app --build-arg VITE_REACT_BACKEND_URL='${{ secrets.VITE_REACT_BACKEND_URL }}'  .

      - name: Publish Image to docker hub
        run: docker push ritik9135/reactjs-app:latest 
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ritik9135/reactjs-app:latest
            docker stop reactjs-frontend || true
            docker rm reactjs-frontend || true
            docker run -d -p 80:80 --restart always --name reactjs-frontend ritik9135/reactjs-app:latest